-- Schema PostgreSQL FanMilk. L'initialisation recommandee reste :
-- docker compose exec vendor-bot flask --app app.main init-db

CREATE TABLE IF NOT EXISTS depots (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(120) NOT NULL UNIQUE,
  location varchar(255) NOT NULL DEFAULT 'Togo',
  active boolean NOT NULL DEFAULT true,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(120) NOT NULL,
  email varchar(255) NOT NULL UNIQUE,
  phone varchar(32) UNIQUE,
  password_hash varchar(255) NOT NULL,
  role varchar(32) NOT NULL CHECK (role IN ('administrateur', 'depositaire', 'revendeur')),
  depot_id integer REFERENCES depots(id),
  active boolean NOT NULL DEFAULT true,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vendors (
  phone varchar(32) PRIMARY KEY,
  name varchar(120) NOT NULL,
  depot_id integer NOT NULL REFERENCES depots(id),
  active boolean NOT NULL DEFAULT true,
  last_declaration_at timestamp,
  last_sales_amount bigint NOT NULL DEFAULT 0,
  last_fanxtra integer NOT NULL DEFAULT 0,
  last_fanchoco integer NOT NULL DEFAULT 0,
  last_fanvanille integer NOT NULL DEFAULT 0,
  last_pieces integer NOT NULL DEFAULT 0,
  last_sales_date date,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku varchar(64) NOT NULL UNIQUE,
  name varchar(120) NOT NULL,
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS sales (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_phone varchar(32) NOT NULL REFERENCES vendors(phone),
  depot_id integer NOT NULL REFERENCES depots(id),
  declared_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  period varchar(16) NOT NULL,
  amount bigint NOT NULL DEFAULT 0,
  location varchar(255) NOT NULL DEFAULT '',
  status varchar(24) NOT NULL DEFAULT 'en_attente' CHECK (status IN ('en_attente', 'validee', 'rejetee')),
  rejection_reason text,
  reviewed_at timestamp,
  reviewed_by integer REFERENCES users(id),
  source varchar(64) NOT NULL DEFAULT 'WhatsApp'
);

CREATE TABLE IF NOT EXISTS sale_lines (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id integer NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
  product_id integer NOT NULL REFERENCES products(id),
  quantity integer NOT NULL DEFAULT 0,
  subtotal bigint NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS stocks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_phone varchar(32) NOT NULL REFERENCES vendors(phone),
  depot_id integer NOT NULL REFERENCES depots(id),
  product_id integer NOT NULL REFERENCES products(id),
  quantity integer NOT NULL,
  declared_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status varchar(24) NOT NULL DEFAULT 'en_attente' CHECK (status IN ('en_attente', 'valide', 'rejete')),
  rejection_reason text,
  reviewed_at timestamp,
  reviewed_by integer REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS difficulties (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_phone varchar(32) NOT NULL REFERENCES vendors(phone),
  depot_id integer NOT NULL REFERENCES depots(id),
  category varchar(120) NOT NULL,
  prime_pillar varchar(64) NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  reported_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  state varchar(24) NOT NULL DEFAULT 'ouverte' CHECK (state IN ('ouverte', 'en_cours', 'resolue')),
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS performances (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_phone varchar(32) NOT NULL REFERENCES vendors(phone),
  depot_id integer NOT NULL REFERENCES depots(id),
  period varchar(32) NOT NULL,
  total_sales bigint NOT NULL DEFAULT 0,
  score double precision NOT NULL DEFAULT 0,
  validated_sales integer NOT NULL DEFAULT 0,
  rejected_sales integer NOT NULL DEFAULT 0,
  UNIQUE (vendor_phone, period)
);

CREATE TABLE IF NOT EXISTS bonuses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_phone varchar(32) NOT NULL REFERENCES vendors(phone),
  depot_id integer NOT NULL REFERENCES depots(id),
  period varchar(32) NOT NULL,
  amount bigint NOT NULL,
  awarded_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  awarded_by integer NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bot_sessions (
  phone varchar(32) PRIMARY KEY,
  step varchar(64) NOT NULL DEFAULT 'start',
  data json NOT NULL DEFAULT '{}'::json,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS processed_messages (
  message_id varchar(191) PRIMARY KEY,
  processed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_sales_depot_status ON sales(depot_id, status);
CREATE INDEX IF NOT EXISTS ix_stocks_depot_status ON stocks(depot_id, status);
CREATE INDEX IF NOT EXISTS ix_difficulties_depot_state ON difficulties(depot_id, state);
CREATE INDEX IF NOT EXISTS ix_vendors_depot_id ON vendors(depot_id);
